### ISSUE TITLE
Java VM warning: ignoring option PerSize

### ISSUE THREAD

**Issue by tolstoi911** [GENIVI/capicxx-core-tools#1]
Version 3.1.0 requires Java 1.8.
Using:

> java version "1.8.0_111"
> Java(TM) SE Runtime Environment (build 1.8.0_111-b14)
> Java HotSpot(TM) 64-Bit Server VM (build 25.111-b14, mixed mode)

gives following warning:

> Generate CommonAPI: ../../interfaces/xyz/xyz.fidl
> Java HotSpot(TM) 64-Bit Server VM warning: ignoring option PermSize=128m; support was removed in 8.0

**Comment by amberbhardwaj** [comment]
Hello @tolstoi911 ,

Can you please share your FIDL file because as per my understanding you're doing something wrong in your FIDL that why this issue comes e.g. used "," or wrong doxygen syntax cause this problem.
 
Note :
While generating the code using commonAPI runtime and commonAPI dus generator, Please make sure that you have updated gcc compiler otherwise you will get lot of compilation error.

**Comment by sorsarre** [comment]
@amberbhardwaj, this is not a fidl-related issue. The option mentioned in the warning is a JVM option, and is defined in the INI files for the generator's binaries. Shouldn't be there anymore with the move to 1.8.

**Comment by tolstoi911** [comment]
@sorsarre:
Right, this is a JVM option (from commonapi-generator-*.ini).
The warning has been introduced with the move to 1.8 (support of the option PermSize was removed with 1.8).

**Comment by GenivivSOMEIPmaintainer** [comment]
PermSize option has been removed in the code generator ini files. Please check current version.
